kind: pipeline
name: default

steps:

  - name: deploy
    image: cupcakearmy/drone-deploy
    pull: always
    settings:
      host: nicco.io
      user: root
      key:
        from_secret: ssh_key
      port: 1312
      test: ok
      # envs: all
      target: /srv/web/test
      commands:
        - echo $HOST
        - echo $TEST
    when:
      event: push
      branch: master